# The Trusty beta Build Environment
sudo: yes
dist: trusty
language: generic

addons:
    postgresql: "9.3"

before_install:
 # exit on fail
 - set -eo pipefail
 # mezuro
 - if ruby --version | cut -d ' ' -f 2 | grep -q 2.1.5p273 ; then gem update --system 2.4.8; fi
 - gem --version

before_script:
    - git clone https://github.com/mezuro/kalibro_install.git -b v4.2 kalibro_install
    - export KALIBRO_CONFIGURATIONS_START=0
    - export KALIBRO_PROCESSOR_START=0
    - pushd kalibro_install
                    
    # Remove bugged libzmq3 package, see https://github.com/travis-ci/travis-ci/issues/982 and https://github.com/travis-ci/travis-ci/issues/1715 for details
    
    # In 2016/04/27 the state is:
    #   * The first issue has been closed and apparently fixed by a PR
    #   * The second one has been closed without a PR and removing the workaround below breaks the build
    
    - sudo apt-get remove libzmq3
    - bash install.sh
    - popd
    - cp config/database.yml.sample config/database.yml
    # Do not run setup as the Kalibro services are up and this is not even necessary!
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - cp features/support/kalibro_cucumber_helpers.yml.sample features/support/kalibro_cucumber_helpers.yml
    - export BUNDLE_GEMFILE=$PWD/Gemfile
    - export CODECLIMATE_REPO_TOKEN=045c2433d496f108c0c6afa5516a72ddbfb1868fb34bf7a9bd095b7a0ea34a79
    
install:
    # update apt-get
    - sudo add-apt-repository --yes ppa:ubuntu-lxc/stable
    - sudo apt-get -qq update
    - sudo apt-get install --yes lxc lxc-templates cgroup-lite redir
    # installing qt files
    - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files
    #- wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
    #- chmod +x qt-opensource-linux-x64-5.7.0.run
    #- ./qt-opensource-linux-x64-5.7.0.run
    # installing QtSpeech
    - sudo apt-get install festival-dev speech-tools
      #- sudo apt-get update && apt-get install festival
    # installing SDL
    - sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
    #installing vagrant
    # - wget https://releases.hashicorp.com/vagrant/2.1.1/vagrant_2.1.1_x86_64.deb
    # - sudo dpkg -i vagrant_2.1.1_x86_64.deb
    # - rm vagrant_2.1.1_x86_64.deb
    # - vagrant plugin install vagrant-lxc
    # installing virtual box
    # - chmod +x virtualbox_install.sh
    #- sudo ./virtualbox_install.sh
    #- sudo /etc/init.d/vboxdrv setup

script:
    - cd OGG/Player
    #- vagrant up
    #- vagrant ssh
    # - cd Documents/Player
    # mezuro
    # Unit tests
    - bundle exec rake spec
    - bundle exec rake konacha:run
    # Start kalibro for acceptance tests
    - pushd kalibro_install
    - bash start_kalibro_services.sh
    - popd
    # Acceptance tests
    - bundle exec rake cucumber
    - qmake "CONFIG+=test" Player.pro #we gonna compile for Unit test first
    - make
    - ./Player #run unit test
    - rm Makefile Player *.o #remove files (which are generated from unit test) for next build

notifications:
      email:
        recipients:
            - bryan_h.f@hotmail.com
        on_success: change
        on_failure: always
