######################################################################
# Automatically generated by qmake (3.0) Wed Jan 31 16:20:01 2018
######################################################################

TEMPLATE = app
TARGET = qtspeech
INCLUDEPATH += .

# Input
HEADERS += QtSpeech.h QtSpeech_unx.h sapi.hh sphelper.hh
SOURCES += guids.c QtSpeech_mac.cpp QtSpeech_unx.cpp QtSpeech_win.cpp
